apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:masters
      rolearn: arn:aws:iam::899676604268:role/UdacityFlaskDeployCBKubectlRole
      username: build
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2021-05-21T18:56:32Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:mapRoles: {}
        f:mapUsers: {}
    manager: eksctl.exe
    operation: Update
    time: "2021-05-21T18:56:32Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1559"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: abb7ef53-6636-46fe-8ad7-efbe8afd981a
