apiVersion: v1
data:
  mapRoles: "- groups:\n  - system:bootstrappers\n  - system:nodes\n  rolearn: arn:aws:iam::899676604268:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-1TIQP1YBKLIZ2\n
    \ username: system:node:{{EC2PrivateDNSName}}\n- groups:\n  - system:masters\n
    \ rolearn: arn:aws:iam::899676604268:role/UdacityFlaskDeployCBKubectlRole\n  username:
    build \n"
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2021-05-22T16:55:36Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:mapUsers: {}
    manager: eksctl.exe
    operation: Update
    time: "2021-05-22T16:55:36Z"
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        f:mapRoles: {}
    manager: kubectl-patch
    operation: Update
    time: "2021-05-22T17:00:30Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "3466"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: bcd65908-a548-456d-a91a-8c1577f146b0
