apiVersion: v1
data:
  mapRoles: |
   - groups:
   - system:masters
   rolearn: arn:aws:iam::899676604268:role/UdacityFlaskDeployCBKubectlRole
   username: build
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::899676604268:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-188KS77T598XZ
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2021-05-22T12:39:44Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:mapRoles: {}
        f:mapUsers: {}
    manager: eksctl.exe
    operation: Update
    time: "2021-05-22T12:39:44Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1572"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: 44fe7fc9-f236-4b69-aa48-bfdfcf124265
